package:
  name: slycot
  version: {{ environ.get('GIT_DESCRIBE_TAG', 'v0.0.0')[1:] }}

source:
  git_url: ../

build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}
  string: py{{ environ.get('PY_VER').replace('.', '') }}{{ environ.get('GIT_DESCRIBE_HASH', '') }}_obl_{{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}

requirements:
  # TODO: pip possibly required in only *one* of build and host, but which?
  build:
    - flang                     # [win]
    - {{ compiler('c') }}
    - {{ compiler('fortran') }} # [unix]

  host:
    - pip
    - python {{ PY_VER }}
    - numpy
    - openblas >=0.3.0
    - scikit-build
   
  run:
    - python {{ PY_VER }}
    - {{ pin_compatible('numpy') }}
    - openblas >=0.3.0

test:
  imports:
    - slycot

about:
  home: https://github.com/python-control/slycot
  license:  GPLv2
  license_family: GPL
  license_file: COPYING
  summary: 'A wrapper for the SLICOT control and systems library'
  description: |
    Slycot wraps the SLICOT library which is used for control and systems
    analysis.

# on OSX, the SDK for 10.9 is currently needed
# download the 10.9 sdk from https://github.com/phracker/MacOSX-SDKs/releases
# unpack and set environment variable CONDA_BUILD_SYSROOT to that location
